### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by Changwei-Ouyang** [AndongDeng/BEAR#2]
I can't download the pre-trained models' checkpoints.

**Comment by AndongDeng** [comment]
Thanks for your interest! We will upload all the pre-trained models this week.

**Comment by Changwei-Ouyang** [comment]
> 感谢您的关注！我们将在本周上传所有预训练的模型。

Thanks for the reply. Very much looking forward to the follow up.

**Comment by AndongDeng** [comment]
@Changwei-Ouyang Hi Changwei, the Dropbox links of the pre-trained models have been uploaded. Feel free to contact us if you have further questions! Thanks!

**Comment by Changwei-Ouyang** [comment]
> @Changwei-Ouyang Hi Changwei, the Dropbox links of the pre-trained models have been uploaded. Feel free to contact us if you have further questions! Thanks!
Thank you very much for your work. I think maybe the self-supervised pre-training weights for the TSM model were missed?

**Comment by AndongDeng** [comment]
@Changwei-Ouyang Thanks for reminding! It's uploaded now!
